sensitiveCodepaths:
  # Files only allowed authors can modify
  # - 'app.js'
  # - 'Makefile'
allowedAuthors:
  usernames:
    # GitHub username
    - 'wickett'
notificationList:
  # GitHub username or team name
  # - '@DryRunSec/security'
  - '@wickett'
